language: cpp
compiler: gcc
before_script:
  - sudo apt-get install libboost-test-dev doxygen -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
script:
  - cmake .
  - cmake --build . 
  - cmake --build . --target package
  - doxygen
before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install: 
  # C++14
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -upro100bac9i:$BINTRAY_API_KEY "https://api.bintray.com/content/pro100bac9i/Otus/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: html
    keep-history: true
    on:
      branch: master